<a href="https://colab.research.google.com/github/ActionMichael/python-training-for-fun/blob/master/Web_Crawler%E5%85%83%E5%A4%A7%E5%8F%B0%E7%81%A3%E9%AB%98%E8%82%A1%E6%81%AF56%E6%88%90%E5%88%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [3]:
url = "https://www.yuantaetfs.com/api/StkWeights?date=&fundid=1084"
df = pd.read_json(url)
df

    code  ym  name                                  ename  weights        qty
0   1101 NaN    台泥                    Taiwan Cement Corp.     3.99   56252497
1   1102 NaN    亞泥                Asia Cement Corporation     3.58   51068008
2   1326 NaN    台化  FORMOSA CHEMICALS & FIBRE CORPORATION     2.21   18321642
3   1605 NaN    華新               WALSIN LIHWA CORPORATION     3.80  188937823
4   2027 NaN   大成鋼        TA CHEN STAINLESS PIPE CO. LTD.     3.40   74844406
5   2301 NaN   光寶科               LITE-ON TECHNOLOGY CORP.     2.76   36675997
6   2324 NaN    仁寶                Compal Electronics Inc.     3.39  105026684
7   2327 NaN    國巨                      YAGEO CORPORATION     3.78    7638173
8   2347 NaN    聯強  Synnex Technology International Corp.     3.47   51978502
9   2356 NaN   英業達                   INVENTEC CORPORATION     3.50   83624123
10  2357 NaN    華碩                  ASUSTEK COMPUTER INC.     2.72    7544609
11  2376 NaN    技嘉          GIGA-BYTE TECHNOLOGY CO. LTD.     3.19   33411892
12  2377 NaN    微星       MICRO-STAR INTERNATIONAL CO.LTD.     3.67   22577786
13  2382 NaN    廣達                   QUANTA COMPUTER INC.     3.15   29029841
14  2385 NaN    群光           CHICONY ELECTRONICS CO. LTD.     2.98   20727253
15  2404 NaN    漢唐    United Integrated Services Co. Ltd.     3.43   11433093
16  2408 NaN   南亞科           NANYA TECHNOLOGY CORPORATION     2.59   26415700
17  2439 NaN    美律              MERRY ELECTRONICS CO.LTD.     2.97   13207428
18  2449 NaN  京元電子         KING YUAN ELECTRONICS CO. LTD.     2.21   40370419
19  2451 NaN    創見             Transcend Information Inc.     3.05   25142789
20  2492 NaN   華新科          WALSIN TECHNOLOGY CORPORATION     5.36   18129933
21  2886 NaN   兆豐金    Mega Financial Holding Company Ltd.     2.98   58334440
22  2915 NaN   潤泰全             RUENTEX INDUSTRIES LIMITED     3.78   30033110
23  3005 NaN    神基           Getac Technology Corporation     3.54   46084180
24  3034 NaN    聯詠         NOVATEK MICROELECTRONICS CORP.     2.07    6509500
25  3231 NaN    緯創                    Wistron Corporation     2.52   56801053
26  3532 NaN   台勝科   FORMOSA SUMCO TECHNOLOGY CORPORATION     5.45   23890170
27  3702 NaN   大聯大                   WPG HOLDINGS LIMITED     3.78   59412726
28  4938 NaN    和碩                   Pegatron Corporation     2.63   24777403
29  6176 NaN    瑞儀         RADIANT OPTO-ELECTRONICS CORP.     2.84   19212469

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   code     30 non-null     int64
 1   ym       0 non-null      float64
 2   name     30 non-null     object
 3   ename    30 non-null     object
 4   weights  30 non-null     float64
 5   qty      30 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.5+ KB